MONGODB_HOST: mongodb.bandarusuresh.in
REDIS_HOST: redis.bandarusuresh.in
CATALOGUE_HOST: catalogue.bandarusuresh.in
CART_HOST: cart.bandarusuresh.in
USER_HOST: user.bandarusuresh.in
RABBITMQ_HOST: rabbitmq.bandarusuresh.in
MYSQL_HOST: mysql.bandarusuresh.in
SHIPPING_HOST: shipping.bandarusuresh.in
PAYMENT_HOST: payment.bandarusuresh.in